# Generated by Django 3.2 on 2022-04-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysubscriptiontransaction',
            options={'verbose_name_plural': 'Company Subscription Transaction'},
        ),
    ]
