# Generated by Django 3.2 on 2022-04-20 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_companysubscriptiontransaction_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companysubscription',
            old_name='end_date',
            new_name='subscription_valid_till',
        ),
        migrations.RemoveField(
            model_name='companysubscriptiontransaction',
            name='subscription_added',
        ),
        migrations.AddField(
            model_name='companysubscriptiontransaction',
            name='subscription_valid',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
