# Generated by Django 3.2 on 2022-04-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220420_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysubscriptiontransaction',
            name='subscription_valid',
        ),
        migrations.AddField(
            model_name='companysubscriptiontransaction',
            name='subscription_duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companysubscriptiontransaction',
            name='subscription_period',
            field=models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=10),
        ),
    ]
