# Generated by Django 3.2 on 2022-04-21 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220420_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_count', models.IntegerField(default=0)),
                ('device_limit', models.IntegerField(default=1)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companysubscription')),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
