# Generated by Django 3.2 on 2022-04-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_device'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='Devices',
        ),
    ]
