# Generated by Django 3.2 on 2022-04-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_device_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.CharField(max_length=100)),
                ('device_user', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Devices History',
            },
        ),
        migrations.AddField(
            model_name='devices',
            name='devices',
            field=models.ManyToManyField(to='users.DevicesHistory'),
        ),
    ]
