# Generated by Django 3.2 on 2022-04-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220421_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='devices',
            field=models.ManyToManyField(blank=True, to='users.DevicesHistory'),
        ),
    ]
