# Generated by Django 3.2 on 2022-04-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_devices_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='devices',
        ),
        migrations.AddField(
            model_name='deviceshistory',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.devices'),
        ),
    ]
