# Generated by Django 3.2 on 2022-04-21 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220421_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceshistory',
            old_name='company',
            new_name='device',
        ),
    ]
