# Generated by Django 3.2 on 2022-04-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_company_deviceshistory_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceshistory',
            name='refresh_token',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
