# Generated by Django 3.2 on 2022-04-12 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('transaction_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_pan', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('taxable_amount', models.FloatField(blank=True, null=True)),
                ('tax_amount', models.FloatField(blank=True, null=True)),
                ('service_amount', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('unpaid', 'Unpaid'), ('cash', 'Cash'), ('credit', 'Credit'), ('card', 'Card'), ('esewa', 'eSewa')], default='unpaid', max_length=10)),
                ('ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('is_realtime', models.BooleanField(default=True)),
                ('vat_refund_amount', models.FloatField(blank=True, null=True)),
                ('sales_return', models.BooleanField(default=False)),
                ('sales_return_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('printed_time', models.DateTimeField(blank=True, null=True)),
                ('sync_with_ird', models.BooleanField(default=False)),
                ('is_bill_printed', models.BooleanField(default=False)),
                ('is_bill_active', models.BooleanField(default=False)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='billing.OrderItem')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.table')),
            ],
        ),
    ]
