# Generated by Django 3.2 on 2022-04-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='default.png', upload_to='img/logo', verbose_name='Company Logo')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('pan_no', models.CharField(max_length=100)),
                ('Tax', models.CharField(blank=True, help_text='Specify Tax in %', max_length=2, null=True)),
                ('service_charge', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(choices=[('NPR', 'NPR'), ('INR', 'INR'), ('USD', 'USD')], max_length=50)),
                ('fiscal_year', models.CharField(max_length=50)),
                ('ird_username', models.CharField(max_length=50)),
                ('ird_password', models.CharField(max_length=50)),
            ],
        ),
    ]
