# Generated by Django 3.2 on 2022-04-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Company Info'},
        ),
    ]
