# Generated by Django 3.2 on 2022-04-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Free'), (0, 'Occupied')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Tables',
            },
        ),
    ]
